import LocalizedStrings from "react-localization";

let strings = new LocalizedStrings({
  en: {
    intro_title: "Harika Çerçevelerimizi",
    intro_subtitle: "Keşfedin",
    intro2_title: "Fotoğraflarınızı ve çerçevelerinizi seçin,",
    intro2_subtitle: "yapışkan bantlar sayesinde duvarlarınızı süsleyin.",
    discover: "Discovery",
    infocard1_title: "Lorem ipsum dior sit amet",
    infocard1_subtitle:
      "Yapışkan bantlar sayesinde duvarlarınıza zarar vermez.",
    infocard2_title: "Türkiye’nin heryerine kargo",
    infocard2_subtitle: "3 çerçeve ve üzeri siparişte ücretsiz kargo fırsatı.",
    infocard3_title: "Farklı model çerçeveler",
    infocard3_subtitle: "Aliquam libero odio, egestas nec gravida sit amet.",
    happy_customer: "Yüzlerce mutlu müşteri",
    contact: "Contact",
    follow_us: "Follow Us",
    sss: "Sık Sorulan Sorular",
    privacy_policy: "Gizlilik Sözleşmesi",
    user_agreement: "Kullanıcı Sözleşmesi",
    live_chat: "Canlı Destek",
    tile_model: "Çerçeve Modeli",
    classic: "Classic",
    pad: "Pad",
    continue: "Continue",
    pickphotos: "Pick Photos",
    yourname: "What's your name?",
    youremail: "What's your email?",
    knowyou: "Let's get to know you",
    letscreategift: "Let's create an amazing gift",
    whositfor: "Who's it for?",
    whattypegift: "What type of gift?",
    formyself: "For myself",
    forsomeoneelse: "For someone else",
    decoratemywalls: "I'm decorating my walls",
    buyinggift: "I'm buying a gift",
    heythere: "Hey there",
    boxpinframes: "A box of Pinframes",
    giftcard: "Gift Card",
    willupload: "I'll upload photos myself",
    choosetheirphotos: "I'll let them choose their own photos",
    valid: " is not a valid email!",
    load_photo: "Fotoğraf Yükle",
    load_with_instagram: "Instagram ile Yükle",
    load_with_facebook: "Facebook ile Yükle",
    privacy_content:
      "Bu internet sitesine veya mobil uygulamaya girmeniz halinde bu internet sitesinde ya da mobil uygulamadaki herhangi bir bilgiyi kullanmanız aşağıdaki koşulları kabul ettiğiniz anlamına gelir.Bu internet sitesine girilmesi veya mobil uygulamanın kullanılması; sitenin ya da sitedeki bilgilerin ve diğer verilerin programların vs. kullanılması sebebiyle, sözleşmenin ihlali, haksız fiil, ya da başkaca sebeplere binaen, doğabilecek doğrudan ya da dolaylı hiçbir zarardan PATH İNTERNET ÇÖZÜM HİZMETLERİ LTD.ŞTİ. (“PATH”) sorumlu değildir. PATH, sözleşmenin ihlali, haksız fiil, ihmal veya diğer sebepler neticesinde; işlemin kesintiye uğraması, hata, ihmal, kesinti hususunda herhangi bir sorumluluk kabul etmez. PATH, internet sitesine girilmesi veya mobil uygulamanın kullanılması yolu ile kullanıcıların, bir başkasına ait IP adresi, elektronik posta adresi, kullanıcı adı gibi kişisel bilgileri kullanması halinde bundan dolayı doğabilecek hiç bir hukuki ve cezai yükümlülüğü kabul etmemektedir.PATH, işbu site ve site uzantısında ya da mobil uygulamada mevcut her tür hizmet, ürün, kullanma koşulları ile sitede ya da mobil uygulamada sunulan bilgileri önceden bir ihtara gerek olmaksızın değiştirme, yeniden organize etme, yayını durdurma hakkını saklı tutar. Değişiklikler sitede ya da mobil uygulamada yayım anında yürürlüğe girer ve değişikliklerin takip edilmesi kullanıcıların sorumluluğu altındadır. Sitenin ya da mobil uygulamanın kullanımı ya da siteye ve mobil uygulamaya giriş ile bu değişiklikler de kabul edilmiş sayılır. Bu koşullar link verilen diğer web sayfaları için de geçerlidir.PATH'in, kullanıcı tarafından siteye ya da mobil uygulamaya kayıt formunda yazılmış olan veya daha sonra kendisi tarafından güncellenen adresi, e-posta adresi, sabit ve mobil telefon hatları ve diğer iletişim bilgileri üzerinden mektup, e-posta, SMS, telefon görüşmesi ve diğer yollarla iletişim, pazarlama, reklam, tanıtım, bildirim ve diğer amaçlarla kullanıcıya ulaşma hakkı bulunmaktadır. Kullanıcı işbu sözleşmeyi kabul etmekle aksine bir yazılı bildirimi olmadığı müddetçe PATH'in kendisine yönelik yukarıda belirtilen iletişim faaliyetlerinde bulunabileceğini kabul ve beyan etmektedir. Kullanıcı, işbu Sözleşmeyi onaylayarak, PATH ile paylaşmış olduğu tüm bilgilerin şahsına ait olduğunu ve bu bilgilerin, satış ve pazarlama faaliyetlerinin yürütülebilmesi amacıyla ve her türlü iletişim aracına uygun bildiriminin sağlanması için tüm Pinframes İştirakleri ile de paylaşılabileceğine onay vermektedir.İnternet sitesinde veya mobil uygulama üzerinde üyelik iptali ve hesap silme işlemi, kullanıcı tarafından yapılabilir. Üyeliğini bitiren kullanıcının internet sitesine ve mobil uygulamaya giriş yetkisi geri dönülmemek üzere iptal edilecektir. PATH’İN kullanıcının kendisi tarafından sonlandırılan kullanıcı hesabına ait her türlü kaydı silip silmeme hakkı saklıdır. Kullanıcı silinen kayıtlarla ilgili herhangi bir hak veya tazminat talebinde bulunamaz.PATH’DEN gönderilen maillerin alt kısmında bulunan “Kampanya duyurularından haberdar olmak istemiyorsanız lütfen tıklayınız.” linkine tıklayarak veya kullanıcı hesabındaki üyelik bilgileri kısmında yer alan ‘’Kampanya duyuruları ile ilgili e-posta almak istiyorum.’’ - ‘’Kampanya duyuruları ile ilgili SMS almak istiyorum.’’ – ‘’ Kampanya duyuruları ile ilgili telefon ile bilgilendirilmek istiyorum.’’ kısmındaki işareti kaldırarak veya gönderilen SMS’lerin içeriğinde yer alan yönlendirme bağlantısı ile günlük ticari ileti gönderim listesinden kolayca ve ücretsiz çıkabilirsiniz.Bu internet sitesi PATH’in kontrolü altında olmayan başka internet sitelerine bağlantı veya referans içerebilir.PATH, bu sitelerin içerikleri veya içerdikleri diğer bağlantılardan sorumlu değildir.PATH bu internet sitesi ve mobil uygulamanın genel görünüm ve dizaynı ile internet sitesi ile mobil uygulamadaki tüm bilgi, resim, Pinframes markası ve diğer markalar, www.Pinframes.com alan adı, logo, ikon, demonstratif, yazılı, elektronik, grafik veya makinede okunabilir şekilde sunulan teknik veriler, bilgisayar yazılımları, uygulanan satış sistemi, iş metodu ve iş modeli de dahil tüm materyallerin (“Materyaller”) ve bunlara ilişkin fikri ve sınai mülkiyet haklarının sahibi veya lisans sahibidir ve yasal koruma altındadır. Internet sitesinde veya mobil uygulamada bulunan hiçbir materyal; önceden izin alınmadan ve kaynak gösterilmeden, kod ve yazılım da dahil olmak üzere, değiştirilemez, kopyalanamaz, çoğaltılamaz, başka bir lisana çevrilemez, yeniden yayımlanamaz, başka bir bilgisayara yüklenemez, postalanamaz, iletilemez, sunulamaz ya da dağıtılamaz. Internet sitesinin veya mobil uygulamanın bütünü veya bir kısmı başka bir internet sitesinde izinsiz olarak kullanılamaz. Aksine hareketler hukuki ve cezai sorumluluğu gerektirir.PATH’in burada açıkça belirtilmeyen diğer tüm hakları saklıdır.İnternet sitesini ve mobil uygulamayı ziyaret eden kullanıcıların bilgileri (ziyaret süresi, zamanı, görüntülenen sayfalar) takip edilmekte ve kayıt altına alınmaktadır. Bu bilgiler, gizlilik koşulları dahilinde, daha iyi hizmet verebilmek, internet sitesinin ve mobil uygulamanın kullanıcılarına sunduğu deneyimi geliştirmek, içeriği genişletmek ve iyileştirmek amacı ile reklam vb. konularda işbirliği yaptığımız firmalarla paylaşılmaktadır.Kullanıcı, kayıt formunu doldurup onayladığı veya bu sistemi kullanarak herhangi bir hizmet almaya başladığı andan itibaren ya da sipariş verdiğinde işbu kullanıcı sözleşmesi yürürlüğe girmektedir. PATH, dilediği zaman işbu sözleşmeyi ve internet sitesindeki ve mobil uygulamada bulunan yasal uyarı sayfasının içeriğini güncelleme hak ve yetkisini saklı tutmaktadır ve kullanıcılarına siteye veya mobil uygulamaya her girişte yasal uyarı ve kullanıcı sözleşmesi sayfasını ziyaret etmelerini tavsiye etmektedir.Müşteri, işbu Gizlilik Sözleşmesini onaylayarak, Pinframes ile paylaşmış olduğu bilgilerin şahsına ait olduğunu ve bu bilgilerin, satış ve pazarlama faaliyetlerinin yürütülebilmesi amacıyla ve her türlü iletişim aracına uygun bildiriminin sağlanması için tüm Pinframes İştirakleri ile de paylaşılabileceğine onay vermektedir.Pinframes, üyelik formlarından topladığı bilgileri, söz konusu üyenin haberi ya da aksi bir talimatı olmaksızın, üçüncü şahıslarla kesinlikle paylaşmamakta, faaliyet dışı hiçbir nedenle ticari amaçla kullanmamakta veya satmamaktadır.Pinframes, e-posta adresleri ve üyelik formlarında istediği kişisel bilgilerin haricinde site kullanımı sırasında izlediği, ziyaretçi hareket ve tercihlerini analiz ederek yorumlamakta veya yorumlatmaktadır. Kişisel bilgiler içermeyen bu istatistiksel veriler, Pinframes.com müşterilerine daha özel ve etkin bir alışveriş deneyimi yaşatmak amacıyla Pinframes iş ortakları ile paylaşılabilmektedir.Müşteri bilgileri, ancak resmi makamlarca usulü dairesinde bu bilgilerin talep edilmesi halinde ve yürürlükteki emredici mevzuat hükümleri gereğince resmi makamlara açıklama yapmak zorunda olduğu durumlarda resmi makamlara açıklanabilecektir.Müşterinin sisteme girdiği tüm bilgilere sadece Müşteri ulaşabilmekte ve bu bilgileri sadece Müşteri değiştirebilmektedir. Bir başkasının bu bilgilere ulaşması ve bunları değiştirmesi mümkün değildir. Müşterinin üyelik adresi ve şifresinin üçüncü bir kişi tarafından biliniyor ve üyeliğin kullanılıyor olmasından dolayı Pinframes kesinlikle sorumlu değildir.Pinframes, müşterilerine daha iyi hizmet verebilmek amacıyla bazı kişisel bilgilerinizi (isim, yaş, ilgi alanlarınız, e-posta vb.) sizlerden talep etmektedir. Pinframes bilgisayarlarında toplanan bu bilgiler, dönemsel kampanya çalışmaları, müşteri profillerine yönelik özel promosyon faaliyetlerinin kurgulanması ve istenmeyen e-postaların iletilmemesine yönelik müşteri “sınıflandırma” ve kişisel bilgiler vasıtasıyla oluşturulacak reklam, tanıtım, pazarlama faaliyetlerinin devam etmesi amacıyla saklanmakta ve bu amaçlarla kullanılmaktadır.Müşteriler, Pinframes.com’dan gönderilen maillerin alt kısmında bulunan “Kampanya duyurularından haberdar olmak istemiyorsanız lütfen tıklayınız.” linkine tıklayarak veya kullanıcı hesabındaki üyelik bilgileri kısmında yer alan ‘’Kampanya duyuruları ile ilgili e-posta almak istiyorum.’’ Ve ‘’Kampanya duyuruları ile ilgili SMS almak istiyorum.’’ Ve ‘’ Kampanya duyuruları ile ilgili telefon ile bilgilendirilmek istiyorum.’’ işaretini kaldırarak veya gönderilen SMS’lerin içeriğinde yer alan yönlendirme bağlantısı ile günlük ticari ileti gönderim listesinden kolayca ve ücretsiz çıkabilmektedir. Ödeme sayfasında istenen kredi kartı bilgileriniz, siteden alışveriş yapan siz değerli müşterilerimizin güvenliğini en üst seviyede tutmak amacıyla hiçbir şekilde www.Pinframes.com veya ona hizmet veren şirketlerin sunucularında tutulmamaktadır. Bu şekilde ödemeye yönelik tüm işlemlerin www.Pinframes.com ara yüzü üzerinden banka ve bilgisayarınız arasında gerçekleşmesi sağlanmaktadır. PATH İNTERNET ÇÖZÜM HİZMETLERİ LTD.ŞTİ.",
    sss_content:
      "Pellentesque malesuada pulvinar lectus id congue 10%. Duis fermentum, ligula at tempus pharetra, libero metus imperdiet metus, a condimentum augue nulla in diam. Cras sit amet turpis sem. Duis fermentum, ligula at tempus pharetra, libero metus imperdiet metus. Duis fermentum, ligula at tempus. Aenean vitae elementum augue. Nunc pharetra faucibus sem ut sodales. Phasellus nec ex mattis lacus vestibulum dignissim. Sed gravida magna tellus, eget facilisis leo ultricies sed. Praesent porta pharetra purus eu dictum. Phasellus vel metus vel odio auctor vestibulum. Aenean nisi dui, porttitor dictum fringilla ac, fermentum a enim. Vivamus tincidunt justo quis turpis mattis egestas. Duis non dolor nisl. Vivamus non aliquet neque. Vestibulum tempus, orci elementum iaculis vestibulum, lectus quam dapibus ex, quis luctus ante lacus id quam. Sed non ante tortor. Nunc quis metus at mauris maximus finibus. Sed pulvinar turpis eu ante laoreet fringilla. Ut varius nisl libero, sit amet euismod mauris sagittis quis. Fusce ac egestas lacus, a sagittis enim. Mauris elementum pellentesque sapien at blandit. Nulla dictum nibh non justo viverra, nec fermentum sapien tempus. Mauris aliquet urna quis pellentesque facilisis. Aliquam nec elementum augue. Etiam porttitor enim et orci maximus consectetur. Nulla et blandit diam. In tortor leo, euismod sit amet felis id, tristique tristique nibh. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Sed dolor arcu, vulputate et tempor vel, rutrum viverra nibh. Nullam nisl sem, varius sit amet nibh a, fermentum facilisis dui. Suspendisse sit amet pellentesque augue. Sed in ante non lacus cursus rhoncus quis vel leo. Duis euismod leo in velit pulvinar posuere. Fusce risus orci, tempor eu faucibus at, pretium ac turpis. Donec id quam ut tellus tempus ultrices et quis tellus. Aenean ac felis nulla. In quis erat eget erat dignissim iaculis. Duis vehicula faucibus quam, id tempor felis ornare eget. In tempus euismod convallis. Vivamus a euismod dui. Praesent consequat nec leo non malesuada. Mauris elementum pellentesque sapien at blandit. Nulla dictum nibh non justo viverra, nec fermentum sapien tempus. Mauris aliquet urna quis pellentesque facilisis. Aliquam nec elementum augue. Etiam porttitor enim et orci maximus consectetur. Nulla et blandit diam. In tortor leo, euismod sit amet felis id, tristique tristique nibh. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Sed dolor arcu, vulputate et tempor vel, rutrum viverra nibh. Nullam nisl sem, varius sit amet nibh a, fermentum facilisis dui. Suspendisse sit amet pellentesque augue. Sed in ante non lacus cursus rhoncus quis vel leo. Duis euismod leo in velit pulvinar posuere. Fusce risus orci, tempor eu faucibus at, pretium ac turpis. Donec id quam ut tellus tempus ultrices et quis tellus. Aenean ac felis nulla. In quis erat eget erat dignissim iaculis. Duis vehicula faucibus quam, id tempor felis ornare eget. In tempus euismod convallis. Vivamus a euismod dui. Praesent consequat nec leo non malesuada.",
    warning: "Warning",
    delete_content: "Are you delete picture ?",
    ok_text: "Ok",
    cancel_text: "Cancel",
    edit: "Edit",
    apply: "Apply",
    order_summary: "Order Summary",
    order_complete: "Order Complete",
    add_delivery: "Add Delivery Information",
    add_card: "Add Card",
    add_promo_code: "Add Promo Code",
    save: "Save",
    add_card_info: "Add Card Information",
    promo_placeholder: "Enter promo code...",
    suggest_friends: "Suggest To Friends",
    payment_success: "Your payment has been successfully completed.",
    payment_failed:
      "The payment failed. Please check the card information and try again.",
    card_user_name: "Kart sahibinin adı soyadı",
    cardnumber: "Kart numarası",
    mounth: "Ay",
    year: "Year",
    name: "İsim",
    surname: "Soyisim",
    tel: "Telefon Numarası",
    email: "E-posta",
    address_title: "Adres Başlığı",
    city: "İl",
    town: "İlçe",
    address: "Açık adres yazınız…",
    distancesellingcontract: "Distance Selling Contract",
    blog: "Blog",
    kvkk: "KVKK",
  },
  tr: {
    intro_title: "Harika Çerçevelerimizi",
    intro_subtitle: "Keşfedin",
    intro2_title: "Fotoğraflarınızı ve çerçevelerinizi seçin,",
    intro2_subtitle: "yapışkan bantlar sayesinde duvarlarınızı süsleyin.",
    discover: "Keşfet",
    infocard1_title: "Lorem ipsum dior sit amet",
    infocard1_subtitle:
      "Yapışkan bantlar sayesinde duvarlarınıza zarar vermez.",
    infocard2_title: "Türkiye’nin heryerine kargo",
    infocard2_subtitle: "3 çerçeve ve üzeri siparişte ücretsiz kargo fırsatı.",
    infocard3_title: "Farklı model çerçeveler",
    infocard3_subtitle: "Aliquam libero odio, egestas nec gravida sit amet.",
    happy_customer: "Yüzlerce mutlu müşteri",
    contact: "Hakkımızda",
    follow_us: "Bizi Takip Edin",
    sss: "Sık Sorulan Sorular",
    privacy_policy: "Gizlilik Sözleşmesi",
    user_agreement: "Kullanıcı Sözleşmesi",
    live_chat: "Canlı Destek",
    tile_model: "Çerçeve Modeli",
    classic: "Classic",
    pad: "Pad",
    continue: "Devam Et",
    pickphotos: "Fotoğraf Seç",
    yourname: "İsminiz nedir?",
    youremail: "E-postanız nedir?",
    knowyou: "Seni Tanıyalım",
    letscreategift: "Hadi harika bir hediye yaratalım",
    whositfor: "Kimin için?",
    whattypegift: "Ne tür bir hediye?",
    formyself: "Kendim için",
    forsomeoneelse: "Başka birisi için",
    decoratemywalls: "Duvarlarımı dekore ediyorum",
    buyinggift: "Hediye alıyorum",
    heythere: "Selam",
    boxpinframes: "Bir kutu Pinframe",
    giftcard: "Hediye Kartı",
    willupload: "Fotoğrafları kendim yükleyeceğim",
    choosetheirphotos: "Kendi fotoğraflarını seçmelerine izin vereceğim",
    valid: " e-posta geçerli değil!",
    load_photo: "Fotoğraf Yükle",
    load_with_instagram: "Instagram ile Yükle",
    load_with_facebook: "Facebook ile Yükle",
    privacy_content:
      "Bu internet sitesine veya mobil uygulamaya girmeniz halinde bu internet sitesinde ya da mobil uygulamadaki herhangi bir bilgiyi kullanmanız aşağıdaki koşulları kabul ettiğiniz anlamına gelir.Bu internet sitesine girilmesi veya mobil uygulamanın kullanılması; sitenin ya da sitedeki bilgilerin ve diğer verilerin programların vs. kullanılması sebebiyle, sözleşmenin ihlali, haksız fiil, ya da başkaca sebeplere binaen, doğabilecek doğrudan ya da dolaylı hiçbir zarardan PATH İNTERNET ÇÖZÜM HİZMETLERİ LTD.ŞTİ. (“PATH”) sorumlu değildir. PATH, sözleşmenin ihlali, haksız fiil, ihmal veya diğer sebepler neticesinde; işlemin kesintiye uğraması, hata, ihmal, kesinti hususunda herhangi bir sorumluluk kabul etmez. PATH, internet sitesine girilmesi veya mobil uygulamanın kullanılması yolu ile kullanıcıların, bir başkasına ait IP adresi, elektronik posta adresi, kullanıcı adı gibi kişisel bilgileri kullanması halinde bundan dolayı doğabilecek hiç bir hukuki ve cezai yükümlülüğü kabul etmemektedir.PATH, işbu site ve site uzantısında ya da mobil uygulamada mevcut her tür hizmet, ürün, kullanma koşulları ile sitede ya da mobil uygulamada sunulan bilgileri önceden bir ihtara gerek olmaksızın değiştirme, yeniden organize etme, yayını durdurma hakkını saklı tutar. Değişiklikler sitede ya da mobil uygulamada yayım anında yürürlüğe girer ve değişikliklerin takip edilmesi kullanıcıların sorumluluğu altındadır. Sitenin ya da mobil uygulamanın kullanımı ya da siteye ve mobil uygulamaya giriş ile bu değişiklikler de kabul edilmiş sayılır. Bu koşullar link verilen diğer web sayfaları için de geçerlidir.PATH'in, kullanıcı tarafından siteye ya da mobil uygulamaya kayıt formunda yazılmış olan veya daha sonra kendisi tarafından güncellenen adresi, e-posta adresi, sabit ve mobil telefon hatları ve diğer iletişim bilgileri üzerinden mektup, e-posta, SMS, telefon görüşmesi ve diğer yollarla iletişim, pazarlama, reklam, tanıtım, bildirim ve diğer amaçlarla kullanıcıya ulaşma hakkı bulunmaktadır. Kullanıcı işbu sözleşmeyi kabul etmekle aksine bir yazılı bildirimi olmadığı müddetçe PATH'in kendisine yönelik yukarıda belirtilen iletişim faaliyetlerinde bulunabileceğini kabul ve beyan etmektedir. Kullanıcı, işbu Sözleşmeyi onaylayarak, PATH ile paylaşmış olduğu tüm bilgilerin şahsına ait olduğunu ve bu bilgilerin, satış ve pazarlama faaliyetlerinin yürütülebilmesi amacıyla ve her türlü iletişim aracına uygun bildiriminin sağlanması için tüm Pinframes İştirakleri ile de paylaşılabileceğine onay vermektedir.İnternet sitesinde veya mobil uygulama üzerinde üyelik iptali ve hesap silme işlemi, kullanıcı tarafından yapılabilir. Üyeliğini bitiren kullanıcının internet sitesine ve mobil uygulamaya giriş yetkisi geri dönülmemek üzere iptal edilecektir. PATH’İN kullanıcının kendisi tarafından sonlandırılan kullanıcı hesabına ait her türlü kaydı silip silmeme hakkı saklıdır. Kullanıcı silinen kayıtlarla ilgili herhangi bir hak veya tazminat talebinde bulunamaz.PATH’DEN gönderilen maillerin alt kısmında bulunan “Kampanya duyurularından haberdar olmak istemiyorsanız lütfen tıklayınız.” linkine tıklayarak veya kullanıcı hesabındaki üyelik bilgileri kısmında yer alan ‘’Kampanya duyuruları ile ilgili e-posta almak istiyorum.’’ - ‘’Kampanya duyuruları ile ilgili SMS almak istiyorum.’’ – ‘’ Kampanya duyuruları ile ilgili telefon ile bilgilendirilmek istiyorum.’’ kısmındaki işareti kaldırarak veya gönderilen SMS’lerin içeriğinde yer alan yönlendirme bağlantısı ile günlük ticari ileti gönderim listesinden kolayca ve ücretsiz çıkabilirsiniz.Bu internet sitesi PATH’in kontrolü altında olmayan başka internet sitelerine bağlantı veya referans içerebilir.PATH, bu sitelerin içerikleri veya içerdikleri diğer bağlantılardan sorumlu değildir.PATH bu internet sitesi ve mobil uygulamanın genel görünüm ve dizaynı ile internet sitesi ile mobil uygulamadaki tüm bilgi, resim, Pinframes markası ve diğer markalar, www.Pinframes.com alan adı, logo, ikon, demonstratif, yazılı, elektronik, grafik veya makinede okunabilir şekilde sunulan teknik veriler, bilgisayar yazılımları, uygulanan satış sistemi, iş metodu ve iş modeli de dahil tüm materyallerin (“Materyaller”) ve bunlara ilişkin fikri ve sınai mülkiyet haklarının sahibi veya lisans sahibidir ve yasal koruma altındadır. Internet sitesinde veya mobil uygulamada bulunan hiçbir materyal; önceden izin alınmadan ve kaynak gösterilmeden, kod ve yazılım da dahil olmak üzere, değiştirilemez, kopyalanamaz, çoğaltılamaz, başka bir lisana çevrilemez, yeniden yayımlanamaz, başka bir bilgisayara yüklenemez, postalanamaz, iletilemez, sunulamaz ya da dağıtılamaz. Internet sitesinin veya mobil uygulamanın bütünü veya bir kısmı başka bir internet sitesinde izinsiz olarak kullanılamaz. Aksine hareketler hukuki ve cezai sorumluluğu gerektirir.PATH’in burada açıkça belirtilmeyen diğer tüm hakları saklıdır.İnternet sitesini ve mobil uygulamayı ziyaret eden kullanıcıların bilgileri (ziyaret süresi, zamanı, görüntülenen sayfalar) takip edilmekte ve kayıt altına alınmaktadır. Bu bilgiler, gizlilik koşulları dahilinde, daha iyi hizmet verebilmek, internet sitesinin ve mobil uygulamanın kullanıcılarına sunduğu deneyimi geliştirmek, içeriği genişletmek ve iyileştirmek amacı ile reklam vb. konularda işbirliği yaptığımız firmalarla paylaşılmaktadır.Kullanıcı, kayıt formunu doldurup onayladığı veya bu sistemi kullanarak herhangi bir hizmet almaya başladığı andan itibaren ya da sipariş verdiğinde işbu kullanıcı sözleşmesi yürürlüğe girmektedir. PATH, dilediği zaman işbu sözleşmeyi ve internet sitesindeki ve mobil uygulamada bulunan yasal uyarı sayfasının içeriğini güncelleme hak ve yetkisini saklı tutmaktadır ve kullanıcılarına siteye veya mobil uygulamaya her girişte yasal uyarı ve kullanıcı sözleşmesi sayfasını ziyaret etmelerini tavsiye etmektedir.Müşteri, işbu Gizlilik Sözleşmesini onaylayarak, Pinframes ile paylaşmış olduğu bilgilerin şahsına ait olduğunu ve bu bilgilerin, satış ve pazarlama faaliyetlerinin yürütülebilmesi amacıyla ve her türlü iletişim aracına uygun bildiriminin sağlanması için tüm Pinframes İştirakleri ile de paylaşılabileceğine onay vermektedir.Pinframes, üyelik formlarından topladığı bilgileri, söz konusu üyenin haberi ya da aksi bir talimatı olmaksızın, üçüncü şahıslarla kesinlikle paylaşmamakta, faaliyet dışı hiçbir nedenle ticari amaçla kullanmamakta veya satmamaktadır.Pinframes, e-posta adresleri ve üyelik formlarında istediği kişisel bilgilerin haricinde site kullanımı sırasında izlediği, ziyaretçi hareket ve tercihlerini analiz ederek yorumlamakta veya yorumlatmaktadır. Kişisel bilgiler içermeyen bu istatistiksel veriler, Pinframes.com müşterilerine daha özel ve etkin bir alışveriş deneyimi yaşatmak amacıyla Pinframes iş ortakları ile paylaşılabilmektedir.Müşteri bilgileri, ancak resmi makamlarca usulü dairesinde bu bilgilerin talep edilmesi halinde ve yürürlükteki emredici mevzuat hükümleri gereğince resmi makamlara açıklama yapmak zorunda olduğu durumlarda resmi makamlara açıklanabilecektir.Müşterinin sisteme girdiği tüm bilgilere sadece Müşteri ulaşabilmekte ve bu bilgileri sadece Müşteri değiştirebilmektedir. Bir başkasının bu bilgilere ulaşması ve bunları değiştirmesi mümkün değildir. Müşterinin üyelik adresi ve şifresinin üçüncü bir kişi tarafından biliniyor ve üyeliğin kullanılıyor olmasından dolayı Pinframes kesinlikle sorumlu değildir.Pinframes, müşterilerine daha iyi hizmet verebilmek amacıyla bazı kişisel bilgilerinizi (isim, yaş, ilgi alanlarınız, e-posta vb.) sizlerden talep etmektedir. Pinframes bilgisayarlarında toplanan bu bilgiler, dönemsel kampanya çalışmaları, müşteri profillerine yönelik özel promosyon faaliyetlerinin kurgulanması ve istenmeyen e-postaların iletilmemesine yönelik müşteri “sınıflandırma” ve kişisel bilgiler vasıtasıyla oluşturulacak reklam, tanıtım, pazarlama faaliyetlerinin devam etmesi amacıyla saklanmakta ve bu amaçlarla kullanılmaktadır.Müşteriler, Pinframes.com’dan gönderilen maillerin alt kısmında bulunan “Kampanya duyurularından haberdar olmak istemiyorsanız lütfen tıklayınız.” linkine tıklayarak veya kullanıcı hesabındaki üyelik bilgileri kısmında yer alan ‘’Kampanya duyuruları ile ilgili e-posta almak istiyorum.’’ Ve ‘’Kampanya duyuruları ile ilgili SMS almak istiyorum.’’ Ve ‘’ Kampanya duyuruları ile ilgili telefon ile bilgilendirilmek istiyorum.’’ işaretini kaldırarak veya gönderilen SMS’lerin içeriğinde yer alan yönlendirme bağlantısı ile günlük ticari ileti gönderim listesinden kolayca ve ücretsiz çıkabilmektedir. Ödeme sayfasında istenen kredi kartı bilgileriniz, siteden alışveriş yapan siz değerli müşterilerimizin güvenliğini en üst seviyede tutmak amacıyla hiçbir şekilde www.Pinframes.com veya ona hizmet veren şirketlerin sunucularında tutulmamaktadır. Bu şekilde ödemeye yönelik tüm işlemlerin www.Pinframes.com ara yüzü üzerinden banka ve bilgisayarınız arasında gerçekleşmesi sağlanmaktadır. PATH İNTERNET ÇÖZÜM HİZMETLERİ LTD.ŞTİ.",
    sss_content:
      "Pellentesque malesuada pulvinar lectus id congue 10%. Duis fermentum, ligula at tempus pharetra, libero metus imperdiet metus, a condimentum augue nulla in diam. Cras sit amet turpis sem. Duis fermentum, ligula at tempus pharetra, libero metus imperdiet metus. Duis fermentum, ligula at tempus. Aenean vitae elementum augue. Nunc pharetra faucibus sem ut sodales. Phasellus nec ex mattis lacus vestibulum dignissim. Sed gravida magna tellus, eget facilisis leo ultricies sed. Praesent porta pharetra purus eu dictum. Phasellus vel metus vel odio auctor vestibulum. Aenean nisi dui, porttitor dictum fringilla ac, fermentum a enim. Vivamus tincidunt justo quis turpis mattis egestas. Duis non dolor nisl. Vivamus non aliquet neque. Vestibulum tempus, orci elementum iaculis vestibulum, lectus quam dapibus ex, quis luctus ante lacus id quam. Sed non ante tortor. Nunc quis metus at mauris maximus finibus. Sed pulvinar turpis eu ante laoreet fringilla. Ut varius nisl libero, sit amet euismod mauris sagittis quis. Fusce ac egestas lacus, a sagittis enim. Mauris elementum pellentesque sapien at blandit. Nulla dictum nibh non justo viverra, nec fermentum sapien tempus. Mauris aliquet urna quis pellentesque facilisis. Aliquam nec elementum augue. Etiam porttitor enim et orci maximus consectetur. Nulla et blandit diam. In tortor leo, euismod sit amet felis id, tristique tristique nibh. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Sed dolor arcu, vulputate et tempor vel, rutrum viverra nibh. Nullam nisl sem, varius sit amet nibh a, fermentum facilisis dui. Suspendisse sit amet pellentesque augue. Sed in ante non lacus cursus rhoncus quis vel leo. Duis euismod leo in velit pulvinar posuere. Fusce risus orci, tempor eu faucibus at, pretium ac turpis. Donec id quam ut tellus tempus ultrices et quis tellus. Aenean ac felis nulla. In quis erat eget erat dignissim iaculis. Duis vehicula faucibus quam, id tempor felis ornare eget. In tempus euismod convallis. Vivamus a euismod dui. Praesent consequat nec leo non malesuada. Mauris elementum pellentesque sapien at blandit. Nulla dictum nibh non justo viverra, nec fermentum sapien tempus. Mauris aliquet urna quis pellentesque facilisis. Aliquam nec elementum augue. Etiam porttitor enim et orci maximus consectetur. Nulla et blandit diam. In tortor leo, euismod sit amet felis id, tristique tristique nibh. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Sed dolor arcu, vulputate et tempor vel, rutrum viverra nibh. Nullam nisl sem, varius sit amet nibh a, fermentum facilisis dui. Suspendisse sit amet pellentesque augue. Sed in ante non lacus cursus rhoncus quis vel leo. Duis euismod leo in velit pulvinar posuere. Fusce risus orci, tempor eu faucibus at, pretium ac turpis. Donec id quam ut tellus tempus ultrices et quis tellus. Aenean ac felis nulla. In quis erat eget erat dignissim iaculis. Duis vehicula faucibus quam, id tempor felis ornare eget. In tempus euismod convallis. Vivamus a euismod dui. Praesent consequat nec leo non malesuada.",
    warning: "Warning",
    delete_content: "Are you delete picture ?",
    ok_text: "Ok",
    cancel_text: "Cancel",
    edit: "Düzenleme",
    apply: "Uygula",
    order_summary: "Sipariş Özeti",
    order_complete: "Siparişi Tamamla",
    add_delivery: "Teslimat Bilgisi Ekle",
    add_card: "Kart Ekle",
    add_promo_code: "Promosyon Kodu Ekle",
    save: "Kaydet",
    add_card_info: "Kart Bilgisi Ekle",
    promo_placeholder: "Kodu giriniz…",
    suggest_friends: "Arkadaşlarına Öner",
    payment_success: "Ödemeniz başarılı bir şekilde tamamlanmıştır.",
    payment_failed:
      "Ödeme işlemi başarısız oldu. Lütfen kart bilgilerini kontrol edip tekrar deneyin.",
    card_user_name: "Kart sahibinin adı soyadı",
    cardnumber: "Kart numarası",
    mounth: "Ay",
    year: "Year",
    name: "İsim",
    surname: "Soyisim",
    tel: "Telefon Numarası",
    email: "E-posta",
    address_title: "Adres Başlığı",
    city: "İl",
    town: "İlçe",
    address: "Açık adres yazınız…",
    distancesellingcontract: "Mesafeli Satış Sözleşmesi",
    blog: "Blog",
    kvkk: "KVKK",
  },
});

export default strings;
